### ISSUE TITLE
Spawn Locations Spawning at Default Fivem Spawn

### ISSUE THREAD

**Issue by Killa-7n39** [ND-Framework/ND_CharacterSelection#9]
Latest ND_Characters, all spawns arent working properly, those spawn players at 0.32, 1.49 idk what z is cause i spawn under the map

**Comment by davefl67** [comment]
The default spawn is at (0.00, 0.00, 0.00) under the map. Heading is also 0.00.
![image](https://github.com/ND-Framework/ND_Characters/assets/107778859/f152940b-25d6-4caf-b32c-3e2319f6991d)

**Comment by davefl67** [comment]
This has been tested on *all* of the spawn positions on the main login screen, all go to the same zero location under the map. If I were a "real server" with players, this would be problematic. For the time being, I have simply been spawning at "last location."

[/davefl67] aka Dave Gaffer (as if there were any doubt!) I am sure my smiley gives me away.
